### ISSUE TITLE
does not work anymore

### ISSUE THREAD

**Issue by kabengwa** [philippmahlow/shopware-docker-stack#3]
Pulling shopware_test_shop (mittwald/shopware:latest)...
ERROR: repository mittwald/shopware not found: does not exist or no pull access
what could be the issue here?

**Comment by philippmahlow** [comment]
Hi,
the image is supposed to be built locally as described in the readme.

Actually this repo was maintained a long time ago und won‘t work without some work. Feel free to publish a pull request ;)
